name: Flomo Reminder
on:
  schedule:
    - cron: "0 12,18 * * *"
jobs:
  run_flomo_reminder:
    name: Run Flomo Reminder
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm install
      - env:
          FLOMO_SALT: ${{ secrets.FLOMO_SALT }}
          FLOMO_AUTHORIZATION: ${{ secrets.FLOMO_AUTHORIZATION }}
          PUSH_URL: ${{ secrets.PUSH_URL }}
        run: npm start
